In [1]:
import numpy as np


In [2]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [5]:

x=np.array([[1,2,3],[4,5,7]])

In [6]:
x

array([[1, 2, 3],
       [4, 5, 7]])

In [7]:
np.shape(x)

(2, 3)

In [8]:
np.size(x)

6

In [9]:
np.ndim(x)

2

In [11]:
x.itemsize

4

# reshape

In [12]:
x.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [7]])

In [13]:
x.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 7]])

In [14]:
x[:1]

array([[1, 2, 3]])

In [15]:
x[0,2]

3

In [16]:
x[1,1]

5

In [17]:
x[0:,0]

array([1, 4])

In [18]:
x[:,0]

array([1, 4])

In [19]:
x[:,-1]

array([3, 7])

In [20]:
x

array([[1, 2, 3],
       [4, 5, 7]])

In [22]:
x[:,0:2]

array([[1, 2],
       [4, 5]])

In [23]:
x[:,0::2]

array([[1, 3],
       [4, 7]])

In [24]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [25]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
x[:1]

array([[1, 2, 3]])

In [28]:
x[2]

array([7, 8, 9])

In [30]:
x[:,2]

array([3, 6, 9])

In [31]:
x[1:,0::2]

array([[4, 6],
       [7, 9]])

In [32]:
x.min()

1

In [33]:
x.max()

9

In [34]:
x.sum()

45

In [35]:
x.mean()

5.0

##columns(axis=0)
##rows(axis=1)

In [36]:
x.sum(axis=1)

array([ 6, 15, 24])

In [37]:
np.sqrt(x)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [38]:
np.std(x)

2.581988897471611

In [39]:
### Vertical and horizontal stacking

In [44]:
a=np.array([[1,3,5],[3,4,5],[7,8,9]])
a

array([[1, 3, 5],
       [3, 4, 5],
       [7, 8, 9]])

In [45]:
b=np.array([[2,3,4],[5,6,7],[8,9,5]])
b

array([[2, 3, 4],
       [5, 6, 7],
       [8, 9, 5]])

In [46]:
np.ravel((a,b))

array([1, 3, 5, 3, 4, 5, 7, 8, 9, 2, 3, 4, 5, 6, 7, 8, 9, 5])

In [47]:
np.vstack((a,b))

array([[1, 3, 5],
       [3, 4, 5],
       [7, 8, 9],
       [2, 3, 4],
       [5, 6, 7],
       [8, 9, 5]])

In [48]:
np.hstack((a,b))

array([[1, 3, 5, 2, 3, 4],
       [3, 4, 5, 5, 6, 7],
       [7, 8, 9, 8, 9, 5]])

In [49]:
np.arange(1,5)

array([1, 2, 3, 4])

In [50]:
np.sin(a)

array([[ 0.84147098,  0.14112001, -0.95892427],
       [ 0.14112001, -0.7568025 , -0.95892427],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [51]:
np.cos(a)

array([[ 0.54030231, -0.9899925 ,  0.28366219],
       [-0.9899925 , -0.65364362,  0.28366219],
       [ 0.75390225, -0.14550003, -0.91113026]])

## Pandas

## to display in structured format

In [52]:
import pandas as pd

In [53]:
dir(pd)

['Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NaT',
 'Panel',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseArray',
 'SparseDataFrame',
 'SparseDtype',
 'SparseSeries',
 'TimeGrouper',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_hashtable',
 '_lib',
 '_libs',
 '_np_version_under1p13',
 '_np_version_under1p14',
 '_np_version_under1p15',
 '_np_version_under1p16',
 '_np_version_under1p17

## Creating a series datatype

In [55]:
s=pd.Series([1,2,3,4,5,6])
s

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [58]:
s=pd.Series([1,2,3,4,5,6],index=['x','y','z','a','b','c'])

In [59]:
s

x    1
y    2
z    3
a    4
b    5
c    6
dtype: int64

In [60]:
help(pd.merge)

Help on function merge in module pandas.core.reshape.merge:

merge(left, right, how='inner', on=None, left_on=None, right_on=None, left_index=False, right_index=False, sort=False, suffixes=('_x', '_y'), copy=True, indicator=False, validate=None)
    Merge DataFrame or named Series objects with a database-style join.
    
    The join is done on columns or indexes. If joining columns on
    columns, the DataFrame indexes *will be ignored*. Otherwise if joining indexes
    on indexes or indexes on a column or columns, the index will be passed on.
    
    Parameters
    ----------
    left : DataFrame
    right : DataFrame or named Series
        Object to merge with.
    how : {'left', 'right', 'outer', 'inner'}, default 'inner'
        Type of merge to be performed.
    
        * left: use only keys from left frame, similar to a SQL left outer join;
          preserve key order.
        * right: use only keys from right frame, similar to a SQL right outer join;
          preserve key 

## Data frame

In [62]:
v1=[1,2,3,4]
v2=[2,5,8,9]
df=pd.DataFrame({'x':v1,'y':v2})

In [63]:
df

x  y
0  1  2
1  2  5
2  3  8
3  4  9

In [64]:
df.isnull()

x      y
0  False  False
1  False  False
2  False  False
3  False  False

# operations in pandas::
## Slicing
## Merging and joining
## Concatenation
## changing the index
## change column headers
## Data Munging

In [1]:
data=[[20,32,34,1],[4,5,67],[23,45,67],[8,9,6,4]]

In [7]:
import pandas as pd
df1=pd.DataFrame({'x1':[10,20,30,11],'y1':[11,12,13,14]},index=['a','b','c','d'],dtype=float)

In [8]:
df1

x1    y1
a  10.0  11.0
b  20.0  12.0
c  30.0  13.0
d  11.0  14.0

In [9]:
data=[[12,1,2,11],[23,21,43,53],[23,32,2,33],[22,1,212]]

In [10]:
df=pd.DataFrame(data,columns=['x1','x2','x3','x4'])


In [11]:
df

x1  x2   x3    x4
0  12   1    2  11.0
1  23  21   43  53.0
2  23  32    2  33.0
3  22   1  212   NaN

In [12]:
df.isnull()

x1     x2     x3     x4
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False  False   True

In [13]:
df.values

array([[ 12.,   1.,   2.,  11.],
       [ 23.,  21.,  43.,  53.],
       [ 23.,  32.,   2.,  33.],
       [ 22.,   1., 212.,  nan]])

In [14]:
df.ndim

2

In [15]:
### Head and Tail

In [16]:
df.head()

x1  x2   x3    x4
0  12   1    2  11.0
1  23  21   43  53.0
2  23  32    2  33.0
3  22   1  212   NaN

In [17]:
df.head(2)

x1  x2  x3    x4
0  12   1   2  11.0
1  23  21  43  53.0

In [18]:
df.tail(1)

x1  x2   x3  x4
3  22   1  212 NaN

In [19]:
df.tail(2)

x1  x2   x3    x4
2  23  32    2  33.0
3  22   1  212   NaN

In [20]:
### Merging and joining

In [26]:
data=[[11,12,14],[22,23,24,25],[33,34,35,36],[43,444,45,46]]
df1=pd.DataFrame(data,columns=['x1','x2','x3','x4'])
df1

x1   x2  x3    x4
0  11   12  14   NaN
1  22   23  24  25.0
2  33   34  35  36.0
3  43  444  45  46.0

In [30]:
pd.merge(df,df1)

Empty DataFrame
Columns: [x1, x2, x3, x4]
Index: []

In [43]:
df

x1  x2   x3    x4
0  12   1    2  11.0
1  23  21   43  53.0
2  23  32    2  33.0
3  22   1  212   NaN

In [32]:
## joining::two different columns,different elements
